#!/usr/bin/env python3
"""Physics-faithful finger model builder (shared).

``high_fidelity/finger.xml`` is auto-generated by ``interactive_viewer.py``
and uses a *spatial* point-site tendon meant for visualisation. That tendon
has a moment arm that grows ~3x with flexion, a compliant (100000 N/m) string,
and soft joint limits — none of which match the real hardware.

This module turns that CAD-geometry XML into a *physics-faithful* model by
swapping in:

  * a **fixed tendon** with a constant sheath moment arm (a steel string in a
    sheath at the flexor offset gives an essentially constant, flip-free arm),
  * a **near-inextensible** tendon stiffness (steel string),
  * **near-rigid joint limits** so the mechanical stops are hard,
  * a small enough timestep for those stiff limits.

The geometry (bodies, masses, joint axes, link lengths, the ``tip`` site) is
taken verbatim from the input XML, so regenerating finger.xml only changes
geometry — the physics fidelity lives here and can be pulled into any script:

    from finger_model import load_fidelity_model
    model = load_fidelity_model("high_fidelity/finger.xml")

or, to tweak a parameter (e.g. once the CAD moment arm is finalised):

    model = load_fidelity_model("high_fidelity/finger.xml", moment_arm=0.0085)
"""
import os
import re
import sys

import mujoco

_REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)
import config  # noqa: E402  — single source of truth
from analytical_model import moment_arm_at_angle  # noqa: E402

# =====================================================================
# Defaults — pulled from config.py; override per-call via
# load_fidelity_model(...) / build_fidelity_xml(...) kwargs.
# =====================================================================
SHEATH_MOMENT_ARM = config.SHEATH_MOMENT_ARM
TENDON_STIFFNESS = config.TENDON_STIFFNESS
TENDON_DAMPING = config.TENDON_DAMPING
SIM_TIMESTEP = config.SIM_TIMESTEP
LIMIT_SOLREF = config.LIMIT_SOLREF
LIMIT_SOLIMP = config.LIMIT_SOLIMP

JOINT_NAMES = config.JOINT_NAMES


def build_fidelity_xml(base_xml_path, out_path=None, *,
                       moment_arm=SHEATH_MOMENT_ARM,
                       tendon_stiffness=TENDON_STIFFNESS,
                       tendon_damping=TENDON_DAMPING,
                       timestep=SIM_TIMESTEP,
                       limit_solref=LIMIT_SOLREF,
                       limit_solimp=LIMIT_SOLIMP,
                       add_tip_site=True):
    """Read ``base_xml_path``, apply the fidelity surgery, write and return
    the path to the built XML.

    Parameters mirror the module-level defaults so a caller can change the
    sheath moment arm or any other setting in one place.
    """
    with open(base_xml_path) as f:
        xml = f.read()

    # 1) timestep
    xml = re.sub(r'(<option[^>]*timestep=")[^"]*(")',
                 rf'\g<1>{timestep}\g<2>', xml)

    # 2) hard joint limits on the default <joint> (applies to all hinges).
    #    Match any stiffness value so this stays robust if the default joint
    #    stiffness changes in config.py.
    xml = re.sub(
        r'(<joint type="hinge"[^>]*?stiffness="[\d.]+")\s*/>',
        rf'\g<1> limited="true" solreflimit="{limit_solref}" '
        rf'solimplimit="{limit_solimp}"/>',
        xml)

    # 3) ensure a 'tip' site on the distal body for link-length extraction
    if add_tip_site and 'name="tip"' not in xml:
        xml = xml.replace(
            '<site name="dip_anchor"',
            '<site name="tip" pos="-0.035800 0.000000 0.000000" '
            'size="0.001" rgba="0.2 0.7 0.95 1"/>\n        '
            '<site name="dip_anchor"', 1)

    # 4) spatial flexor tendon -> fixed constant-moment-arm tendon.
    #    coef is negative so flexion (positive theta) SHORTENS the tendon,
    #    matching a flexor (pulling the string flexes the joint).
    c = moment_arm
    joints = "\n".join(
        f'      <joint joint="{j}" coef="{-c}"/>' for j in JOINT_NAMES)
    fixed = (
        '  <tendon>\n'
        '    <!-- fixed tendon: L = sum_i (coef_i * theta_i); coef = constant\n'
        '         sheath moment arm.  Built by finger_model.build_fidelity_xml. -->\n'
        f'    <fixed name="flexor" stiffness="{tendon_stiffness}" '
        f'damping="{tendon_damping}" springlength="-1">\n'
        f'{joints}\n'
        '    </fixed>\n'
        '  </tendon>')
    xml = re.sub(r'  <tendon>.*?</tendon>', fixed, xml, flags=re.DOTALL)

    if out_path is None:
        base_dir = os.path.dirname(os.path.abspath(base_xml_path))
        out_path = os.path.join(base_dir, "_finger_fidelity.xml")
    with open(out_path, "w") as f:
        f.write(xml)
    return out_path


def load_fidelity_model(base_xml_path, *, disable_gravity=True,
                        disable_contact=True, **build_kwargs):
    """Build the faithful XML and return a loaded ``mujoco.MjModel``.

    ``build_kwargs`` are forwarded to :func:`build_fidelity_xml` (e.g.
    ``moment_arm=0.0085``).  Gravity and contacts are disabled by default
    since the quasi-static morphology study is contact-free.
    """
    path = build_fidelity_xml(base_xml_path, **build_kwargs)
    model = mujoco.MjModel.from_xml_path(path)
    if disable_gravity:
        model.opt.gravity[:] = 0.0
    if disable_contact:
        model.opt.disableflags |= mujoco.mjtDisableBit.mjDSBL_CONTACT
    return model


def update_fixed_tendon_moment_arms(model, data, r0=None):
    """Make MuJoCo's effective tendon moment arm angle-dependent.

    A MuJoCo ``<fixed>`` tendon has CONSTANT joint coefficients, so to follow the
    measured angle-dependent moment-arm curve (``config.MOMENT_ARM_CURVE_*`` — the
    same table the analytical model uses) we rewrite those coefficients in place,
    once per simulation step, from the CURRENT joint angles:

        coef_i = -moment_arm_at_angle(theta_i, r0)

    (negative = flexor: positive flexion shortens the tendon). Call this right
    before ``mujoco.mj_step`` in every stepped loop. No-op when
    ``config.MOMENT_ARM_ANGLE_DEPENDENT`` is False (the constant 0-deg arm baked
    into the XML is preserved). Only JOINT wraps are touched, so a spatial tendon
    (site/pulley wraps), if any, is left alone.
    """
    if not getattr(config, "MOMENT_ARM_ANGLE_DEPENDENT", False):
        return
    if r0 is None:
        r0 = config.SHEATH_MOMENT_ARM
    for t in range(model.ntendon):
        adr = model.tendon_adr[t]
        for w in range(adr, adr + model.tendon_num[t]):
            if model.wrap_type[w] != mujoco.mjtWrap.mjWRAP_JOINT:
                continue
            jid = int(model.wrap_objid[w])
            theta = float(data.qpos[model.jnt_qposadr[jid]])
            model.wrap_prm[w] = -float(moment_arm_at_angle(theta, r0))
